name: 'Copy to Remote'
on:
  workflow_dispatch:

jobs:
  copy_to_remote:
    runs-on: ubuntu-latest
    env:
      REMOTE_REPO: 'https://github.com/natepage/poc-copy-remote.git'
    steps:
      - uses: eonx-com/actions-checkout@v2

      - name: 'Remove Git Extra Header'
        run: 'git config -l | grep ''http\..*\.extraheader'' | cut -d= -f1 | xargs -L1 git config --unset-all'

      - name: 'Copy files to remote repo'
        run: |          
          echo 'Clone remote repo and remove all files but .git folder'
          git clone $REMOTE_REPO $GITHUB_WORKSPACE/../remote
          find $GITHUB_WORKSPACE/../remote/ -type f -not -name '.git*' -delete
          
          echo ''
          echo 'Remove git context and copy files from github workspace to remote repo'
          rm -rf $GITHUB_WORKSPACE/.git
          cp -r $GITHUB_WORKSPACE/* $GITHUB_WORKSPACE/../remote/
          
          echo ''
          echo 'Add, commit, and push changes to remote repo'
          cd $GITHUB_WORKSPACE/../remote/
          git init
          git add .
          git commit -m 'Copy files to remote'
          git branch -M main
          git remote add origin $REMOTE_REPO
          git push -u origin main

#      - run: 'git fetch --prune --unshallow'
#
#
#
#      - name: 'Resolve current branch'
#        id: branch_name
#        run: 'echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"'
#
#      - name: 'Add Repo Remote'
#        run: 'git remote add split-remote https://natepage:${{ secrets.MONOREPO_GITHUB_TOKEN }}@github.com/eonx-com/${{ matrix.mapping.repo }}.git'
#
#      - name: 'Split packages/${{ matrix.mapping.dir }}'
#        env:
#          BRANCH: '${{ steps.branch_name.outputs.branch }}'
#        run: |
#          git checkout -b "local-$BRANCH-checkout" "$BRANCH"
#          git subtree split --prefix="packages/${{ matrix.mapping.dir }}" --branch="local-$BRANCH" "$BRANCH"
#          git push --force split-remote local-$BRANCH:$BRANCH
#
#      - if: 'contains(github.event.head_commit.message, ''[Release]'')'
#        name: 'Release eonx-com/${{ matrix.mapping.repo }}:${{ matrix.tag }}'
#        shell: bash
#        run: |
#          if git rev-parse "$TAG" >/dev/null 2>&1; then
#              git checkout -b "local-$TAG-checkout" "tags/$TAG"
#
#              if [ -d "$DIR" ]; then
#                  git subtree split --prefix="$DIR" --branch="local-$TAG" "$TAG"
#                  git push --force split-remote local-$TAG:refs/tags/$TAG
#              else
#                  echo "Dir \"$DIR\" does not exist for tag \"$TAG\""
#              fi
#          else
#              echo "Tag \"$TAG\" does not exist, skip"
#          fi
