name: 'Copy to Remote'
on:
  workflow_dispatch:

jobs:
  copy_to_remote:
    runs-on: ubuntu-latest
    env:
      GITHUB_ORG: 'natepage'
      GITHUB_USERNAME: 'natepage'
      GITHUB_EMAIL: 'nathan.page@eonx.com'
      GITHUB_TOKEN: '${{ secrets.COPY_TO_REMOTE_GITHUB_TOKEN }}'
      GITHUB_TARGET_BRANCH: 'main'
      GITHUB_REMOTE_REPO: 'poc-copy-remote'
    steps:
      - uses: eonx-com/actions-checkout@v2

      - name: 'Remove Git Extra Header'
        run: 'git config -l | grep ''http\..*\.extraheader'' | cut -d= -f1 | xargs -L1 git config --unset-all'

      - name: 'Copy files to remote repo'
        run: |
          git config --global user.email "$GITHUB_EMAIL"
          git config --global user.name "$GITHUB_USERNAME"
          
          GITHUB_FULL_REMOTE_REPO=https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/$GITHUB_ORG/$GITHUB_REMOTE_REPO.git
          
          echo 'Clone remote repo and remove all files but .git folder'
          git clone --single-branch --depth 1 --branch "$GITHUB_TARGET_BRANCH" "$GITHUB_FULL_REMOTE_REPO" "$GITHUB_WORKSPACE/../remote"
          #find $GITHUB_WORKSPACE/../remote/ -type f -not -name '.git*' -delete
          
          echo ''
          echo 'Remove git context and copy files from github workspace to remote repo'
          rm -rf $GITHUB_WORKSPACE/.git
          cp -r $GITHUB_WORKSPACE/* $GITHUB_WORKSPACE/../remote/
          
          echo ''
          echo 'Add, commit, and push changes to remote repo'
          cd $GITHUB_WORKSPACE/../remote/
          git add .
          git commit -m 'Copy files to remote'
          git push "$GITHUB_FULL_REMOTE_REPO" --set-upstream "$GITHUB_TARGET_BRANCH"
